apiVersion: v1
kind: Service
metadata:
  name: shrink-analyzer-ui
spec:
  selector:
    app: shrink-analyzer-ui
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shrink-analyzer-ui
spec:
  selector:
    matchLabels:
      app: shrink-analyzer-ui
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: shrink-analyzer-ui
    spec:
      containers:
      - name: shrink-analyzer-ui
        image: us-east1-docker.pkg.dev/shoppertrak-repo/shrink-analyzer-ui:latest
        ports:
        - containerPort: 80
        env:
          - name: API_URL
            value: "https://webapi-kubernetes-testing.appname.com"        
